# Generated by Django 4.1.3 on 2022-12-27 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameOver', models.BooleanField(default=False)),
                ('playerTurn', models.SlugField(default='WHITE')),
                ('selectedPieceCordinates', models.CharField(max_length=15, null=True)),
                ('moveToCordinates', models.CharField(max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chessboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chessboard', models.JSONField()),
                ('gameState', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chessengine.gamestate')),
            ],
        ),
    ]
