# Generated by Django 5.0.7 on 2024-08-09 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameStateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameOver', models.BooleanField(default=False)),
                ('playerTurn', models.SlugField(default='WHITE')),
                ('totalMoves', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ChessMoveModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piece', models.JSONField(default=None)),
                ('move', models.JSONField(default=None)),
                ('position', models.JSONField(default=None)),
                ('pieceTaken', models.JSONField(default=None)),
                ('result', models.TextField(null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('gameState', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chessengine.gamestatemodel')),
            ],
        ),
        migrations.CreateModel(
            name='ChessBoardModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chessboard', models.JSONField()),
                ('moveDict', models.JSONField(null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('playerTurn', models.TextField(max_length=15)),
                ('gameState', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chessengine.gamestatemodel')),
            ],
        ),
    ]
