# Generated by Django 4.1.4 on 2023-03-28 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameStateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameOver', models.BooleanField(default=False)),
                ('playerTurn', models.SlugField(default='WHITE')),
                ('totalMoves', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ChessBoardMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cords', models.JSONField()),
                ('result', models.TextField(null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('gameState', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chessengine.gamestatemodel')),
            ],
        ),
        migrations.CreateModel(
            name='ChessboardModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chessboard', models.JSONField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('playerTurn', models.TextField(max_length=15)),
                ('gameState', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chessengine.gamestatemodel')),
            ],
        ),
    ]
