# Generated by Django 4.1.3 on 2022-12-27 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chessengine', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chessboard',
            new_name='ChessboardModel',
        ),
        migrations.RenameModel(
            old_name='GameState',
            new_name='GameStateModel',
        ),
    ]
