# Generated by Django 4.1.4 on 2023-01-01 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chessengine', '0004_remove_gamestatemodel_movetocordinates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chessboardmodel',
            name='playerTurn',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
