# Generated by Django 4.1.4 on 2023-01-01 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chessengine', '0006_alter_chessboardmodel_playerturn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chessboardmodel',
            name='playerTurn',
            field=models.TextField(max_length=15),
        ),
    ]
